spring:
  application:
    name: JobSeekPro

  datasource:
    url: jdbc:postgresql://localhost:5432/jobseekdb
    username: jobseekuser
    password: jobseekpass
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s


  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
#    deserialization:
#      adjust-dates-to-context-time-zone: false


  batch:
    datasource:
      url: jdbc:postgresql://localhost:5432/jobseekdb
      username: jobseekuser
      password: jobseekpass
      driver-class-name: org.postgresql.Driver
    jdbc:
      initialize-schema: always
      table-prefix: BATCH_



server:
  port: 8080


logging:
  level:
    root: INFO
    com.ft.searchengine: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.springframework.batch: DEBUG